### ISSUE TITLE
Gerência de Carteiras

### ISSUE THREAD

**Issue by fillipefeitosa** [fabraz/assetcheef#3]
---------------------------------
Investidor Gerente deseja  gerenciar as carteiras do investidor B. Sendo que o investidor B acessará apenas os resultados de sua carteira.

**Comment by alvarofernandoms** [comment]
O investidor A pode ter várias carteiras, ou pode gerenciar as carteiras do investidor B. Sendo que o investidor B acessará apenas os resultados de sua carteira.

**Comment by fillipefeitosa** [comment]
Investidor 1 : N Carteiras

**Comment by fillipefeitosa** [comment]
Investidor Gerente 1 : N Investidor

**Comment by fillipefeitosa** [comment]
Sugestão: Relatórios e Gráficos
